version: 2
jobs:
  build:
    steps:
      - checkout
      - run: make
  test:
    steps:
      - checkout
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
